version: 0.2

env:
  variables:
    DESTROY: "true"   # Set to "true" for destruction or "false" for deployment
    
phases:
  install:
    runtime-versions:
      golang: latest
    commands:
      - echo Installing dependencies...
      - sudo yum update -y
      - sudo yum install -y yum-utils
      - sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - sudo yum -y install terraform
      - terraform --version
      - echo Installing AWS CLI...
      - sudo yum install -y aws-cli

  build:
    commands:
      - |
        cd Terraform/Terraform
        if [[ "$DESTROY" == "true" ]]; then
          echo "Running Terraform destroy..."
          terraform init
          terraform plan --var-file=config/destroy.tfvars -out=tfplan-destroy
          terraform destroy --var-file=config/destroy.tfvars -auto-approve
        else
          echo "Running Terraform deployment..."
          echo Starting RDS instance ..
          terraform init
          terraform plan --var-file=config/deploy.tfvars -out=tfplan
          terraform apply --var-file=config/deploy.tfvars -auto-approve tfplan
        fi

  post_build:
    commands:
      - echo "Pipeline execution completed."

artifacts:
  files:
    - '**/*'
